x-uffizzi:
  ingress:
    service: app
    port: 80

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    environment:
      UUID: afd4eb38-b100-4821-b3b3-8b7394bedf77
      
    restart: always
    ports:
      - "80:80"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
volumes:
  data:

secrets:
  UUID:
    external: true
    name: "UUID"
  NEZHA_SERVER:
    external: true
    name: "NEZHA_SERVER"
  NEZHA_PORT:
    external: true
    name: "NEZHA_PORT"  
  NEZHA_KEY:
    external: true
    name: "NEZHA_KEY"
